use super::*;

pub const DWARVEN_MALE_NAMES: [&'static str; 102] = [
    "Bralgor", "Tharnok", "Dorgath", "Krunir", "Vorlund", "Gromden", "Halthor", 
    "Murden", "Falkrim", "Tharuk", "Harvek", "Baldrek", "Torvik", 
    "Durmak", "Kilgrim", "Garthen", "Vorund", "Thorek", "Mardin", "Brannik", 
    "Jorund", "Haldor", "Karvik", "Fenror", "Brugor", "Tharim", "Ulfden", 
    "Gundar", "Draven", "Torund", "Rurik", "Gorin", "Bramir", "Hargath", 
    "Tholrin", "Dorak", "Rundar", "Kroven", "Gorath", "Haldin", "Thurin", 
    "Brakon", "Durgen", "Krelgor", "Vornin", "Thaldur", "Grendel", "Morkin", 
    "Tarben", "Horgath", "Grundar", "Felrin", "Brundek", "Thalmar", "Garvin", 
    "Krendor", "Dulgath", "Harlin", "Rorvik", "Bronar", "Kelgar", "Thorik", 
    "Fendek", "Thorin", "Gulden", "Marnik", "Vralin", "Tholdun", "Harvok", 
    "Bralden", "Korgath", "Tormin", "Gundrak", "Dornar", "Tharek", 
    "Gorven", "Brundin", "Kelvin", "Thardin", "Marvek", "Grondin", "Thulmar", 
    "Harven", "Drumek", "Torlin", "Vrenor", "Galdor", "Rundin", "Thorgath", 
    "Kraldor", "Bramlin", "Haldar", "Mordak", "Felmar", "Thorgan", "Grimven", 
    "Borlin", "Tharik", "Grundin", "Durin", "Kragan", "Thrain",
];

pub const DWARVEN_FEMALE_NAMES: [&'static str; 100] = [
    "Bryndis", "Thalara", "Gundri", "Marnis", "Dolvira", "Kelta", 
    "Vorgina", "Tharika", "Grimora", "Kavari", "Hildra", "Sigrin", "Dorella",
    "Brelia", "Torina", "Helmira", "Ulma", "Grendil", "Durila", 
    "Yvella", "Karnis", "Morgra", "Jornia", "Brylla", "Fergra", "Vorna", 
    "Keldra", "Grilsa", "Sorna", "Thalga", "Dargia", "Helsa", "Faldin", 
    "Vorlina", "Mirnda", "Krunis", "Borrin", "Thalda", "Kelira", "Hedrin", 
    "Ylria", "Orila", "Mavri", "Grelka", "Tarin", "Jelra", "Korlana", 
    "Tharva", "Brilda", "Vorena", "Durga", "Frina", "Seldra", "Kalmin", 
    "Vandri", "Torla", "Gulda", "Beldra", "Zorla", "Farin", "Norika", 
    "Horga", "Brimi", "Korina", "Durva", "Grinda", "Yolda", 
    "Melsa", "Thora", "Felsa", "Brinda", "Dolria", "Fergun", 
    "Thalida", "Hilda", "Morgin", "Grana", "Kelria", "Varna", 
    "Tholga", "Brodra", "Vorda", "Krenna", "Faldra", "Helina", "Tharvin", 
    "Dorna", "Grella", "Kelda", "Velsa", "Tharna", "Morgil", "Yelva", 
    "Herdra", "Krilin", "Torra", "Vandis", "Erynd", "Brennara", "Thaldis",
];

pub const DWARVEN_SURNAMES: [&'static str; 100] = [
    "Stonehammer", "Ironfist", "Granitebeard", "Boulderfall", "Moltenstorm",
    "Frostshield", "Ironheart", "Stormaxe", "Rockbreaker", "Goldenshield", 
    "Stonebrow", "Thunderstone", "Strongarm", "Earthguard", "Slateshield",
    "Ironpeak", "Gravelvein", "Mountainbender", "Steelstrike", "Flintaxe", 
    "Deepdelver", "Oakenfoot", "Strongshield", "Frostmane", "Hammerfall", 
    "Stonefoot", "Rockwarden", "Stormguard", "Emberforge", "Earthbinder", 
    "Grimstone", "Forgeheart", "Stonewarden", "Ironbeard", "Firebrow", 
    "Steelbreaker", "Earthshaper", "Rockbrow", "Thunderpeak", "Darkbrow", 
    "Granitestorm", "Hammerstone", "Mountainshield", "Strongpeak", "Ironfall", 
    "Bouldervein", "Thunderstrike", "Goldbrow", "Stoneforge", "Ironstorm", 
    "Earthstrike", "Rockhammer", "Gravelguard", "Steelheart", "Darkbreaker", 
    "Granitefoot", "Thunderforge", "Stormwarden", "Hammerpeak", "Earthforge", 
    "Ironstrike", "Flintforge", "Mountainheart", "Steelshield", "Magmafall",
    "Earthbrow", "Strongstone", "Goldstrike", "Rockstrike", "Moltenvein",
    "Granitestone", "Ironshield", "Darkpeak", "Hammerguard", "Stonefall", 
    "Steelpeak", "Thunderheart", "Frostforge", "Earthstorm", "Gravelpeak", 
    "Strongforge", "Rockstorm", "Ironwarden", "Stonepeak", "Darkforge", 
    "Thunderfoot", "Hammerstorm", "Goldforge", "Graniteshield", "Steelguard", 
    "Earthheart", "Rockpeak", "Ironvein", "Thunderbrow", "Gravelstorm", 
    "Stonebender", "Darkstone", "Strongheart", "Goldheart", "Moltenheart",
];
