use super::*;

pub const ELVEN_MALE_NAMES: [&'static str; 101] = [
    "Aelrion", "Baelor", "Caelhan", "Daerion", "Faerel", "Gaelin", 
    "Haemar", "Ithilion", "Jaelar", "Kaelen", "Laeroth", "Maelor", "Naerion", 
    "Oleran", "Paeris", "Raegor", "Saeros", "Taerion", "Ulinar", 
    "Vaelin", "Waesil", "Xaelor", "Yaelion", "Zaelith", "Aeril", "Baelion", 
    "Caelthas", "Daelin", "Eirion", "Faelor", "Gaeris", "Haeril", "Ithren", 
    "Jaelis", "Kaeril", "Laeron", "Maeril", "Naeris", "Olaris", "Paelion", 
    "Quaelis", "Raelion", "Saelir", "Taelis", "Uloris", "Vaeril", "Waelin", 
    "Xarion", "Yaerith", "Zaelor", "Aerion", "Baelith", "Caelor", "Daeron", 
    "Elarin", "Faelir", "Gaelthas", "Haelor", "Ithorin", "Jaerion", "Kaerith", 
    "Laerion", "Maelir", "Naelion", "Olarin", "Paelith", "Quaerion", "Raelir", 
    "Saelion", "Taeril", "Ulinor", "Vaerion", "Waeril", "Xaril", "Yaelir", 
    "Zaelion", "Aelor", "Baelrin", "Caelion", "Daelir", "Elorin", "Faelrin", 
    "Gaelion", "Haelith", "Ithrin", "Jaelrin", "Kaelion", "Laelir", "Maelion", 
    "Naelir", "Olaeris", "Paelrin", "Quaelor", "Raelthas", "Saelrin", "Taelion",
    "Elion", "Malorn", "Arannis", "Thalion", "Eldrin",
];

pub const ELVEN_FEMALE_NAMES: [&'static str; 159] = [
    "Aeliana", "Baelis", "Caelara", "Daerith", "Faelira", 
    "Haelora", "Ithilia", "Jaelira", "Kaelara", "Laerith", "Maelora", "Naelira", 
    "Olaris", "Paelina", "Raelis", "Saelara", "Taelith", "Ulinara", 
    "Vaelina", "Xaelira", "Yaelith", "Zaelira", "Aerith", "Baelora", 
    "Caelis", "Daelina", "Elaria", "Faelis", "Gaelina", "Haelith", "Ithilara", 
    "Jaelina", "Laerina", "Maelith", "Naelina", "Olarith", "Paelith", 
    "Quaelina", "Raelith", "Saelina", "Taelira", "Ulinith", "Vaelith", "Waelina", 
    "Xaelith", "Yaelira", "Zaelina", "Aeloria", "Baelith", "Caelina", "Daelira", 
    "Eloria", "Faelina", "Gaelira", "Haelina", "Ithilith", "Jaelith", "Kaelina", 
    "Laelith", "Maelira", "Naelith", "Olaeria", "Paelira", "Raelina", 
    "Saelith", "Taelina", "Vaelira", "Xaelina", "Yaelina", 
    "Zaelith", "Aerilith", "Baelina", "Caelora", "Daelith", 
    "Haelira", "Jaelora", "Kaelira", "Laelina", 
    "Olarina", "Quaelira", "Saelira", "Aelwen", "Brynneth",
    "Daeliana", "Elowen", "Faelinna", "Gwenaela", 
    "Haelindra", "Iliara", "Jadariel", "Kaelynn", "Lorelei", "Maerwyn", "Nimue", 
    "Orianna", "Phaela", "Quenara", "Ravenna", "Seraphina", "Talindra", "Uriel", 
    "Vaelara", "Wynndara", "Xanthea", "Aeris", 
    "Dianara", "Elyssara", "Faelyn", "Galenia", "Haelara", "Ilyssa", 
    "Jezara", "Liriel", "Mirelle", "Naelara", "Ophira", "Pryssara", 
    "Rielle", "Sylvara", "Thessara", "Ulara", "Vaelora", "Winara", 
    "Xylara", "Ysara", "Zephyra", "Aeriana", "Brielle", "Caelyra", "Delynn", 
    "Elara", "Faelin", "Galadriel", "Ilyana", "Jadara", "Kaelena", 
    "Maelani", "Nyssa", "Oria", "Prynn", "Quenariel", 
    "Sariel", "Urielle", "Wynara", "Xanthe", "Ysariel", 
    "Zephyr", "Aelara", "Brynnara", "Elowyn", "Faelara", 
    "Gwenna", "Iliana", "Lorena", "Maelara", 
    "Nimara", "Oriara", "Phaelara", "Ravara",
];

pub const ELVEN_SURNAMES: [&'static str; 100] = [
    "Amarillis", "Braesilver", "Calaerion", "Duskryn", "Eldertree", "Felarion", 
    "Glimmerdew", "Hawkthorn", "Ilithor", "Jaderune", "Kaelithor", "Lunarain", 
    "Moonshadow", "Nimrathis", "Oakenshade", "Phaerlin", "Quilenor", "Raelithas", 
    "Starfire", "Taranthir", "Ullathor", "Vaerithor", "Windrider", "Xilaryn", 
    "Yllinor", "Zolaris", "Aerindor", "Brightspear", "Calaethis", "Darkwood", 
    "Eveningfall", "Faelivrin", "Goldenleaf", "Havenwood", "Ithildor", "Jalorien", 
    "Keltharion", "Leafsong", "Moonwhisper", "Nightsong", "Oakenwind", "Pyrelight", 
    "Quilendis", "Ravenwind", "Silvertree", "Thalorian", "Ulthorin", "Vallarion", 
    "Windwhisper", "Xarathis", "Yavandir", "Zalorin", "Aerendyl", "Bladewind", 
    "Celendril", "Dawnstrike", "Elensar", "Faerindel", "Graythorn", "Hollywind", 
    "Ilmareth", "Jalarion", "Kethorin", "Lunaris", "Moonglade", "Nightbreeze", 
    "Oakenbark", "Pryndor", "Quindoril", "Rivermist", "Starleaf", "Thalorn", 
    "Ullarion", "Vaelorin", "Windwalker", "Xylathor", "Yavaris", "Zerindor", 
    "Aldermist", "Briarshade", "Caladorn", "Duskfall", "Elarion", "Felathor", 
    "Glynarin", "Halethor", "Ilmaris", "Jorindel", "Kaelindor", "Lorien", 
    "Moonsong", "Nightwind", "Oakenfell", "Prylinor", "Quelindor", "Ravencrest", 
    "Silversong", "Thrandor", "Ullorin", "Vaelithor",
];
